---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`"numero"`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`8`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`16`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`20`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`true`"
  checked: false
name: "¿Y esto cuánto vale?"
